#!/usr/bin/env bash

set -euo pipefail

project_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

exec nix develop "${project_root}" \
  --command make --directory="${project_root}" rebuild
